app:
  db:
    username: blahblahblah
endpoints:
  prometheus:
    sensitive: false
    enabled: true
  env:
    enabled: true
    sensitive: false
  info:
    enabled: true
    sensitive: false
micronaut:
  application:
    name: books
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
  server:
    port: 8081
#kafka:
#  bootstrap:
#    servers: localhost:9092

kafka:
  enabled: false

#kafka:
#  consumers:
#    default:
#      bootstrap.servers: "localhost:9092"
#  producers:
#    default:
#      bootstrap.servers: "localhost:9092"
netty:
  default:
    allocator:
      max-order: 3

team:
  name: 'Steelers'
  color: 'Black'
  player-names:
    - 'Mason Rudolph'
    - 'James Connor'