scrape_configs:
  - job_name: books-app
    scrape_interval: 5s
    metrics_path: '/prometheus'
    static_configs:
      - targets:
          - host.docker.internal:8081
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
          - cadvisor:8080